function resizeImage1() {const img = document.getElementById("imgToSwitch"); img.style.width = "1%"; img.style.height = "auto";}
function resizeImage5() {const img = document.getElementById("imgToSwitch"); img.style.width = "5%"; img.style.height = "auto";}
function resizeImage10() {const img = document.getElementById("imgToSwitch"); img.style.width = "10%"; img.style.height = "auto";}
function resizeImage15() {const img = document.getElementById("imgToSwitch"); img.style.width = "15%"; img.style.height = "auto";}
function resizeImage20() {const img = document.getElementById("imgToSwitch"); img.style.width = "20%"; img.style.height = "auto";}
function resizeImage25() {const img = document.getElementById("imgToSwitch"); img.style.width = "25%"; img.style.height = "auto";}
function resizeImage30() {const img = document.getElementById("imgToSwitch"); img.style.width = "30%"; img.style.height = "auto";}
function resizeImage35() {const img = document.getElementById("imgToSwitch"); img.style.width = "35%"; img.style.height = "auto";}
function resizeImage40() {const img = document.getElementById("imgToSwitch"); img.style.width = "40%"; img.style.height = "auto";}
function resizeImage45() {const img = document.getElementById("imgToSwitch"); img.style.width = "45%"; img.style.height = "auto";}
function resizeImage50() {const img = document.getElementById("imgToSwitch"); img.style.width = "50%"; img.style.height = "auto";}
function resizeImage55() {const img = document.getElementById("imgToSwitch"); img.style.width = "55%"; img.style.height = "auto";}
function resizeImage60() {const img = document.getElementById("imgToSwitch"); img.style.width = "60%"; img.style.height = "auto";}
function resizeImage65() {const img = document.getElementById("imgToSwitch"); img.style.width = "65%"; img.style.height = "auto";}
function resizeImage70() {const img = document.getElementById("imgToSwitch"); img.style.width = "70%"; img.style.height = "auto";}
function resizeImage75() {const img = document.getElementById("imgToSwitch"); img.style.width = "75%"; img.style.height = "auto";}
function resizeImage80() {const img = document.getElementById("imgToSwitch"); img.style.width = "80%"; img.style.height = "auto";}
function resizeImage85() {const img = document.getElementById("imgToSwitch"); img.style.width = "85%"; img.style.height = "auto";}
function resizeImage90() {const img = document.getElementById("imgToSwitch"); img.style.width = "90%"; img.style.height = "auto";}
function resizeImage95() {const img = document.getElementById("imgToSwitch"); img.style.width = "95%"; img.style.height = "auto";}
function resizeImage100() {const img = document.getElementById("imgToSwitch"); img.style.width = "100%"; img.style.height = "auto";}